### ISSUE TITLE
Pre-trained model download

### ISSUE THREAD

**Issue by AlexChyi** [Liu-Feng-deeplearning/CoverHunter#1]
The pre-trained model cannot be downloaded. Could you please open the download permission

**Comment by Liu-Feng-deeplearning** [comment]
sorry i forget to change global access, try it again.


Good luck~~
















At 2023-07-20 16:46:56, "AlexChyi" ***@***.***> wrote:

The pre-trained model cannot be downloaded. Could you please open the download permission
