### ISSUE TITLE
The Impact of Input Length of Audio Segments on mAP

### ISSUE THREAD

**Issue by wang-ironman** [Liu-Feng-deeplearning/CoverHunter#2]
Thank you for your excellent work, it has been very helpful to me. 

According to my test results, I found that **the longer(90s, 135s, 180s) input length of audio segments gets the higher mAP**(at my local dataset,mostly short audio（10s-20s），max length < 90s). However, I am confused because: 
> 1. During the training phase, the first and second stages used 15s/15s-45s. 
> 2. When the length is long, because the input is short audio, so a lot of value(-100) will be padded behind it, it should not bring benefits.

What do you think might be the possible causes of this result?

I would greatly appreciate your reply

**Comment by Liu-Feng-deeplearning** [comment]
I'm not sure if I understand your question well. 

Generally compared with longer length, shorter length leads to decrease of mAP.But we also found that longer audio may be contains some not useful infomation. For example, the audio with 180 seconds, may be contains some free-style part at head or tail, these frames do not have corresponding segments in other cover songs. And we want cut off them in our training. So we do not use the whole audio in our training. 

Another question is about padding of the short audio. In our experiment, almost all audio have 60s or more, and we do not need to consider too short audios. And this paper only focus on the long section(maybe the next paper we will explore more about shorter section).

Hope my reply could help you. Good luck!~~

**Comment by wang-ironman** [comment]
> 
你好。
非常抱歉，我表达的不够清楚，我使用中文提问吧。
对于这句话
>Generally compared with longer length, shorter length leads to decrease of mAP.

一般来说应该是在长音频上成立的吧，长音频输入网络模型前不需要填充或者填充的非常少，但是我们本地数据中的音频很短，例如20s的音频，如果输入长度为180s，那将在其后面填充160s的填充值（-100），填充部分远远多于原始音频，这种情况下为什么也符合“音频越长mAP越高”呢，这是我困惑的地方。因为后面填充的都是无意义的数值，怎么也会对提高mAP有帮助呢？

**Comment by Liu-Feng-deeplearning** [comment]
因为之前的实验，训练和推理都基于较长的音频数据上进行的。包括测试的指标也都在长音频上测试所得。对于短音频，pad 看上去应该不起什么作用。“音频越长mAP越高” 这个结论只针对长音频（不需要pad的情况）。
