### ISSUE TITLE
第一阶段（coarse training）的训练细节

### ISSUE THREAD

**Issue by wang-ironman** [Liu-Feng-deeplearning/CoverHunter#4]
您好，非常感谢您出色的工作，对我帮助很大。

我现在在从头开始复现论文（加入一些中文歌曲数据），在训练第一阶段时，我对于一些细节不太清楚，想请教一下您。
>1. 代码是适用第一阶段的吗？只需要修改数据以及chunk参数
>2. 标注也是使用的song id吗？
>3. 训练了多少个epoch？
>4. 训练的超参数设置以及训练log

非常期待您的答复！

**Comment by Liu-Feng-deeplearning** [comment]
1. 是的。
2. 是的。
3. 50
4. 超参数可以参考config文件。因为某些原因，训练log无法提供。但是，印象中不记得有哪些特别值得注意的现象了。
如果有问题欢迎随时提出。

感谢并祝好运。
