### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by AndyGuo1** [Liu-Feng-deeplearning/CoverHunter#5]
作者您好，能提供一下SHS100K 的CQT 特征嘛。或者怎样去通过YouTube的url去生成SHS100K 的CQT 特征呢

**Comment by Liu-Feng-deeplearning** [comment]
可能需要通过url下载对应的歌曲。项目里有根据音频提特征的函数。

**Comment by AndyGuo1** [comment]
嗯嗯好的。感谢您。
