### ISSUE TITLE
refer confused users to CoverHunterMPS fork?

### ISSUE THREAD

**Issue by alanngnet** [Liu-Feng-deeplearning/CoverHunter#9]
Suggestion to add to the README a reference to the CoverHunterMPS fork, where I've fixed the various bugs, improved performance, added Apple Silicon support, and added a lot more documentation about how to use this project.

https://github.com/alanngnet/CoverHunterMPS

**Comment by Liu-Feng-deeplearning** [comment]
Good idea~~
